### ISSUE TITLE
Стоит сделать расшифровку кодов в столбце страны.

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [Engineer-Petr/Engineer-Petr.github.io#41]
Например, непонятно, что такое 🇺🇸🇨🇦🇬🇧🇩🇪🇮🇪. Может там запятых не хватает?

**Comment by DAlexIV** [comment]
Ага, на винде emoji с флагами не поддерживаются, попробую заменить их картинками

**Comment by DAlexIV** [comment]
Спасибо за замечание, поправил)
