### ISSUE TITLE
Messagebird, the Netherlands

### ISSUE THREAD

**Issue by sintah** [Engineer-Petr/Engineer-Petr.github.io#42]
Careers page: https://messagebird.com/careers/

**Comment by DAlexIV** [comment]
@sintah Thanks for your contribution, I've added it in the list. Could you please clarify whether the company still relocates during coronavirus pandemic?

**Comment by sintah** [comment]
@DAlexIV, during the pandemic new engineers start to work remotely until borders are open with engineer's country. When borders are open, MessageBird will relocate engineers

**Comment by DAlexIV** [comment]
@sintah That's great, I've added that info
