### ISSUE TITLE
Add search keywords

### ISSUE THREAD

**Issue by vrfloppa** [Engineer-Petr/Engineer-Petr.github.io#86]

**Comment by leonid-sviderskii-mtl** [comment]
@vrfloppa It seems the SEO guys says it's kinda useless to add meta keywords as search engines do ignore those.

What they suggest to use is this:

> There are three key areas in which you want to put your keyword phrases:
> 
> Introduction: Put your keywords within the first 100 words of the page.
> Main Content: Put your keywords at least 2-4 times in the main content of the page (evenly spread out).
> Summary: Put your keywords within the last 100 words of the page.

From: https://seochatter.com/how-to-add-keywords-to-a-website-for-seo/

What do you think?

**Comment by vrfloppa** [comment]
> @vrfloppa It seems the SEO guys say it's kinda useless to add meta keywords as search engines do ignore those.
> 
> What they suggest to use is this:
> 
> > There are three key areas in which you want to put your keyword phrases:
> > Introduction: Put your keywords within the first 100 words of the page.
> > Main Content: Put your keywords at least 2-4 times in the main content of the page (evenly spread out).
> > Summary: Put your keywords within the last 100 words of the page.
> 
> Also, we could change the Title of the website - to add something about relocation to the existing `Engineering Petr` one.
> 
> From: https://seochatter.com/how-to-add-keywords-to-a-website-for-seo/
> 
> What do you think the scope should be then?

That's a good point! 
Feel free to change the text on the webpage and the heading. I was also thinking that we may benefit from adding a text in Russian as well.

**Comment by RealTemur** [comment]
Релокация, переезд для айтишников, работа за рубежом для разработчиков, IT remote work, удаленная работа для программистов
