### ISSUE TITLE
Add companies from https://relocate.me/blog/job-relocation/30-foreign-tech-companies-are-ready-to-hire-you-in-2019/

### ISSUE THREAD

**Issue by vrfloppa** [Engineer-Petr/Engineer-Petr.github.io#97]

**Comment by leonid-sviderskii-mtl** [comment]
@vrfloppa do I add all the new companies from there as Great? If not, what's the rule?

**Comment by vrfloppa** [comment]
> @vrfloppa do I add all the new companies from there as Great? If not, what's the rule?

Thanks for asking! I would add all of them to the full list. I add companies to great companies if I heard some positive stuff about them from my friends at this company. If you have a company in mind that should be or shouldn't be in great list, just ping me and lets discuss :)
